### PR TITLE
Update README links

### PR DESCRIPTION
**Pull request by gavinmischler**
#### What does this implement/fix? Explain your changes.
Updates links in the README for new documentation site. Also fix grammar

#### Any other comments?
It looks like our docs badge says "failing" because its' linked to our old NeuroData repository. (https://readthedocs.org/projects/mvlearn/) @rflperry do you have access to the ReadtheDocs page and can you change it?

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by rflperry** [comment]
@gavinmischler I've requested access to the readthedocs from @rguo123

**Comment by rguo123** [comment]
Do you know where you requested this? DId not get any notification about permission requests

**Comment by rflperry** [comment]
@rguo123 in slack, sorry. If you could change the settings in https://readthedocs.org/projects/mvlearn/ to reflect the domain https://mvlearn.github.io or transfer permissions to be to do that, would be great.

**Comment by rguo123** [comment]
I did both

**Pull request merged**
