### PR TITLE
Sphinx gallery setup

### PR DESCRIPTION
**Pull request by agramfort**
done with this mess https://gist.github.com/agramfort/2c2b721a17c435a33e954123d193661f

### CODE REVIEW

**Comment by agramfort** [comment]
@rflperry please have a look. You will see that many examples/notebooks were broken.

my time is pretty much on this. Please take over by pushing directly to this PR

**Comment by agramfort** [comment]
That’s a start https://18-206838300-gh.circle-artifacts.com/0/dev/auto_examples/index.html

Many examples are broken or have a lot of duplicated code
And flake8 issues

**Comment by rflperry** [comment]
Thanks this start is fabulous.

Yes, I've been aware of a lot of these issues but they were not affecting our prior docs and so were low priority. I'll focus on them now and push to this PR.

Will get back to you when this gets resolved.

**Comment by agramfort** [comment]
thanks !

>

**Comment by rflperry** [comment]
@agramfort looks like everything works now.

**Comment by agramfort** [comment]
ok looks good https://64-206838300-gh.circle-artifacts.com/0/dev/auto_examples/index.html

let's iterate from there.

thanks @rflperry

**Pull request merged**
